// src/cli/init-command.ts
import fs from 'fs';
import path from 'path';
import os from 'os';
import * as readline from 'readline';
import { reloadEnv } from '../core/config.js';

// Create single readline interface for all prompts
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

// Helper to read from stdin (works with piped input)
function readFromStdin(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer);
    });
  });
}

export async function deepAgentsInitCommand() {
  console.log(`
╔════════════════════════════════════════╗
║  Deep Agents -- First Time Setup       ║
╚════════════════════════════════════════╝
`);

  // Check if .env.local already exists in home directory
  const envPath = path.join(os.homedir(), '.env.local');
  const hasEnv = fs.existsSync(envPath);

  if (hasEnv) {
    const answer = await readFromStdin('.env.local already exists. Reconfigure? (y/n) [n]: ');
    if (answer.toLowerCase() !== 'y' && answer.toLowerCase() !== 'yes') {
      console.log('Setup complete -- using existing configuration.');
      return;
    }
  }

  console.log(
    'Please provide your LLM API keys:\n' +
    '(You can set these later by editing .env.local)\n'
  );

  // Collect API keys using readline (works with piped stdin)
  const anthropicKey = await readFromStdin(
    'ANTHROPIC_API_KEY (Claude - optional, press Enter to skip): '
  );

  const openaiKey = await readFromStdin(
    'OPENAI_API_KEY (GPT - optional, press Enter to skip): '
  );

  const googleKey = await readFromStdin(
    'GOOGLE_API_KEY (Gemini - optional, press Enter to skip): '
  );

  if (!anthropicKey && !openaiKey && !googleKey) {
    console.log('Error: At least one API key must be provided.');
    return;
  }

  const backendUrl = await readFromStdin('Backend URL (http://localhost:4200): ') || 'http://localhost:4200';

  const dashboardPort = await readFromStdin('Dashboard port (4201): ') || '4201';

  // Create .env.local
  const envContent = `# Deep Agents Configuration
# Generated by buildwithnexus init

# LLM API Keys
${anthropicKey ? `ANTHROPIC_API_KEY=${anthropicKey}` : '# ANTHROPIC_API_KEY='}
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '# OPENAI_API_KEY='}
${googleKey ? `GOOGLE_API_KEY=${googleKey}` : '# GOOGLE_API_KEY='}

# Backend
BACKEND_URL=${backendUrl}
DASHBOARD_PORT=${dashboardPort}

# Optional
# LOG_LEVEL=debug
`;

  fs.writeFileSync(envPath, envContent, { mode: 0o600 });

  reloadEnv(envPath);
  console.log('Configuration saved to .env.local and loaded into environment.');

  // Close readline interface
  rl.close();
}
