// src/cli/init-command.ts
import fs from 'fs';
import path from 'path';
import os from 'os';
import { input, confirm, password } from '@inquirer/prompts';
import { reloadEnv } from '../core/config.js';

export async function deepAgentsInitCommand() {
  console.log(`
╔════════════════════════════════════════╗
║  Deep Agents -- First Time Setup       ║
╚════════════════════════════════════════╝
`);

  // Check if .env.local already exists in home directory
  const envPath = path.join(os.homedir(), '.env.local');
  const hasEnv = fs.existsSync(envPath);

  if (hasEnv) {
    const shouldReset = await confirm({
      message: '.env.local already exists. Reconfigure?',
      default: false,
    });
    if (!shouldReset) {
      console.log('Setup complete -- using existing configuration.');
      return;
    }
  }

  console.log(
    'Please provide your LLM API keys:\n' +
    '(You can set these later by editing .env.local)\n'
  );

  // Collect API keys (using password input for security - shows asterisks)
  const anthropicKey = await password({
    message: 'ANTHROPIC_API_KEY (Claude - optional, press Enter to skip)',
  });

  const openaiKey = await password({
    message: 'OPENAI_API_KEY (GPT - optional, press Enter to skip)',
  });

  const googleKey = await password({
    message: 'GOOGLE_API_KEY (Gemini - optional, press Enter to skip)',
  });

  if (!anthropicKey && !openaiKey && !googleKey) {
    console.log('Error: At least one API key must be provided.');
    return;
  }

  const backendUrl = await input({
    message: 'Backend URL',
    default: 'http://localhost:4200',
  });

  const dashboardPort = await input({
    message: 'Dashboard port',
    default: '4201',
  });

  // Create .env.local
  const envContent = `# Deep Agents Configuration
# Generated by buildwithnexus init

# LLM API Keys
${anthropicKey ? `ANTHROPIC_API_KEY=${anthropicKey}` : '# ANTHROPIC_API_KEY='}
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '# OPENAI_API_KEY='}
${googleKey ? `GOOGLE_API_KEY=${googleKey}` : '# GOOGLE_API_KEY='}

# Backend
BACKEND_URL=${backendUrl}
DASHBOARD_PORT=${dashboardPort}

# Optional
# LOG_LEVEL=debug
`;

  fs.writeFileSync(envPath, envContent, { mode: 0o600 });

  reloadEnv(envPath);
  console.log('Configuration saved to .env.local and loaded into environment.');
}
