// src/cli/init-command.ts
import fs from 'fs';
import path from 'path';
import { input, confirm } from '@inquirer/prompts';

export async function deepAgentsInitCommand() {
  console.log(`
╔════════════════════════════════════════╗
║  Deep Agents -- First Time Setup       ║
╚════════════════════════════════════════╝
`);

  // Check if .env.local already exists
  const envPath = path.join(process.cwd(), '.env.local');
  const hasEnv = fs.existsSync(envPath);

  if (hasEnv) {
    const shouldReset = await confirm({
      message: '.env.local already exists. Reconfigure?',
      default: false,
    });
    if (!shouldReset) {
      console.log('Setup complete -- using existing configuration.');
      return;
    }
  }

  console.log(
    'Please provide your LLM API keys:\n' +
    '(You can set these later by editing .env.local)\n'
  );

  // Collect API keys
  const anthropicKey = await input({
    message: 'ANTHROPIC_API_KEY (Claude)',
    default: '',
    validate: (val) => {
      if (!val) {
        return 'At least one API key is required';
      }
      return true;
    },
  });

  const openaiKey = await input({
    message: 'OPENAI_API_KEY (GPT - optional)',
    default: '',
  });

  const backendUrl = await input({
    message: 'Backend URL',
    default: 'http://localhost:4200',
  });

  const dashboardPort = await input({
    message: 'Dashboard port',
    default: '4201',
  });

  // Create .env.local
  const envContent = `# Deep Agents Configuration
# Generated by buildwithnexus init

# LLM API Keys
ANTHROPIC_API_KEY=${anthropicKey}
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '# OPENAI_API_KEY='}

# Backend
BACKEND_URL=${backendUrl}
DASHBOARD_PORT=${dashboardPort}

# Optional
# LOG_LEVEL=debug
`;

  fs.writeFileSync(envPath, envContent);

  console.log(`
Configuration saved to .env.local

Next steps:
  1. Start the backend:
     cd ~/Projects/nexus && python -m src.deep_agents_server

  2. Start the dashboard:
     buildwithnexus dashboard

  3. Run your first task:
     deep-agents run "List files in the current directory"

For help, run:
  deep-agents --help
`);
}
